# Generated by Django 4.0.6 on 2022-08-04 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_farm_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='farm_location',
        ),
        migrations.AddField(
            model_name='location',
            name='lan',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
