# Generated by Django 4.0.6 on 2022-08-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_location_farm_location_location_lan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lan',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='longitude',
        ),
    ]
