# Generated by Django 4.0.6 on 2022-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_rename_lan_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
