# Generated by Django 4.0.6 on 2022-07-22 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='phone',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
