# Generated by Django 4.0.6 on 2022-07-24 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extenduser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='isCodeVerified',
            field=models.BooleanField(default=False),
        ),
    ]
