# Generated by Django 4.0.6 on 2022-07-25 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extenduser_code_extenduser_iscodeverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='firstName',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='firstName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extenduser',
            name='lastName',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='lastName'),
            preserve_default=False,
        ),
    ]
