# Generated by Django 4.0.6 on 2022-07-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='describtion',
            new_name='description',
        ),
    ]
