# Generated by Django 4.0.6 on 2022-08-13 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_describtion_farm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='culture',
            field=models.CharField(default='nothing', max_length=251),
        ),
        migrations.AddField(
            model_name='farm',
            name='work',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
