# Generated by Django 4.0.6 on 2022-08-19 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_farm_culture_farm_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=650),
            preserve_default=False,
        ),
    ]
