# Generated by Django 4.0.6 on 2022-07-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='szcondName',
            new_name='secondName',
        ),
    ]
