# Generated by Django 4.0.6 on 2022-08-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_rename_szcondname_worker_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='workField',
            field=models.CharField(default=1, max_length=251),
            preserve_default=False,
        ),
    ]
